# Superset Helm Chart Values
# Business Intelligence for Lakehouse Enterprise

image:
  repository: apache/superset
  tag: 2.1.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8088
  annotations: {}

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2000m
    memory: 2Gi

postgresql:
  enabled: true
  auth:
    postgresPassword: superset123
    username: superset
    password: superset123
    database: superset
  primary:
    persistence:
      enabled: true
      size: 20Gi

redis:
  enabled: true
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 8Gi

supersetNode:
  replicaCount: 1
  connections:
    redis_host: superset-redis-master
    redis_port: "6379"
    db_host: superset-postgresql
    db_port: "5432"
    db_user: superset
    db_pass: superset123
    db_name: superset

init:
  adminUser:
    username: admin
    firstname: Admin
    lastname: User
    email: admin@superset.com
    password: admin123
  createAdmin: true
  loadExamples: false

configOverrides:
  secret: |
    SECRET_KEY = 'thisISaSECRET_1234'
    SQLALCHEMY_DATABASE_URI = 'postgresql://superset:superset123@superset-postgresql:5432/superset'
    CACHE_CONFIG = {
        'CACHE_TYPE': 'redis',
        'CACHE_DEFAULT_TIMEOUT': 300,
        'CACHE_KEY_PREFIX': 'superset_',
        'CACHE_REDIS_HOST': 'superset-redis-master',
        'CACHE_REDIS_PORT': 6379,
        'CACHE_REDIS_DB': 1,
        'CACHE_REDIS_URL': 'redis://superset-redis-master:6379/1'
    }
    DATA_CACHE_CONFIG = CACHE_CONFIG

