apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hive-metastore
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/lakehouse-enterprise
    path: infra/hive-metastore
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: hive-metastore
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  revisionHistoryLimit: 10
  
  # Dependências - PostgreSQL deve estar pronto primeiro
  info:
    - name: 'Dependencies'
      value: 'postgresql'
  
  ignoreDifferences:
    - group: batch
      kind: Job
      jsonPointers:
        - /spec/template/spec/containers/0/env

