apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trino
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  sources:
    - repoURL: https://trinodb.github.io/charts
      chart: trino
      targetRevision: 0.8.0
      helm:
        valueFiles:
          - /home/dissertio/lakehouse-enterprise/infra/trino/values.yaml
    - repoURL: https://github.com/fabiojssouza/lakehouse-enterprise.git  # SUBSTITUIR pela URL do seu repositório
      targetRevision: HEAD
      ref: values
  
  destination:
    server: https://kubernetes.default.svc
    namespace: trino
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  revisionHistoryLimit: 10
  
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas

